### ISSUE TITLE
multi-region events

### ISSUE THREAD

**Issue by hawo1** [Permiso-io-tools/CloudConsoleCartographer#1]
with "aws cloudtrail lookup-events " you can just collect events from a specific region. When a user clicks in region eu-west-1 to iam and creates a user then these events will be logged to cloudtrail in us-east-1.  So to create a complete event summery CloudConsoleCartographer would need to be able to analyse multiple regional lookup-sources. 

Have you already thought about that or am I missing something?

**Comment by dbo-at-permiso** [comment]
Cloud Console Cartographer consumes whatever events you feed it. It's primary focus is on correlation regardless of which region the log originates. So you can feed it logs gathered from multiple regions and it will handle re-ordering by eventTime and performing the correlation.
